CXXC=g++ -g #-fsanitize=address
CXXFLAGS= -std=c++14 -W -Wall -Wextra -Werror -Wfatal-errors #-Weffc++
LDFLAGS= -lallegro -lallegro_primitives -lallegro_ttf -lallegro_font
EXEC=main
SRC= $(wildcard *.cpp)
OBJ=$(SRC:.cpp=.oo)

all: $(EXEC)

main: $(OBJ)
	$(CXXC) -o $@ $^ $(LDFLAGS)

%.oo: %.cpp
	$(CXXC) -o $@ -c $< $(CXXFLAGS)

.PHONY: clean pc


clean: 
	rm -rf *.oo $(EXEC)

